remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Piotr Parkitny]
description: Explore my data-driven projects and analyses that cover everything from machine learning to data visualization.

avatar: /images/avatar.png
profile_picture: /images/avatar.png
