remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/leap-day@v0.2.0
#remote_theme: pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme 

title: Piotr Parkitny
description: Explore my data-driven projects and analyses that cover everything from machine learning to data visualization.

avatar: /images/piotr_parkitny.jpg
profile_picture: /images/piotr_parkitny.jpg
logo: /images/piotr_parkitny.jpg

# Custom CSS
#sass:
#  style: compressed
#include:
#  - assets/css/style.css